#指定 mapper 文件路径
mybatis:
  mapper-locations: classpath:mapper/xml/ds1/*.xml
  configuration:
    cache-enabled: false
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #打印 SQL 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl