server:
  port: 2211
  servlet:
    context-path: /wxmOpencv



#
#  spring.servlet.multipart.max-file-size=10MB
#  spring.servlet.multipart.max-request-size=10MB
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
